package com.hjwblog.robo_cmp.model.mapper;

import com.hjwblog.robo_cmp.model.CmpResult;
import com.hjwblog.robo_cmp.model.CmpResultCriteria;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CmpResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @SelectProvider(type = CmpResultSqlProvider.class, method = "countByExample")
    int countByExample(CmpResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @DeleteProvider(type = CmpResultSqlProvider.class, method = "deleteByExample")
    int deleteByExample(CmpResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @Delete({
            "delete from t_cmp_result",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @Insert({
            "insert into t_cmp_result (id, service, ",
            "container, params, ",
            "result)",
            "values (#{id,jdbcType=INTEGER}, #{service,jdbcType=VARCHAR}, ",
            "#{container,jdbcType=VARCHAR}, #{params,jdbcType=LONGVARCHAR}, ",
            "#{result,jdbcType=LONGVARCHAR})"
    })
    int insert(CmpResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @InsertProvider(type = CmpResultSqlProvider.class, method = "insertSelective")
    int insertSelective(CmpResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @SelectProvider(type = CmpResultSqlProvider.class, method = "selectByExampleWithBLOBs")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "service", property = "service", jdbcType = JdbcType.VARCHAR),
            @Result(column = "container", property = "container", jdbcType = JdbcType.VARCHAR),
            @Result(column = "params", property = "params", jdbcType = JdbcType.LONGVARCHAR),
            @Result(column = "result", property = "result", jdbcType = JdbcType.LONGVARCHAR)
    })
    List<CmpResult> selectByExampleWithBLOBs(CmpResultCriteria example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @SelectProvider(type = CmpResultSqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "service", property = "service", jdbcType = JdbcType.VARCHAR),
            @Result(column = "container", property = "container", jdbcType = JdbcType.VARCHAR),
            @Result(column = "params", property = "params", jdbcType = JdbcType.LONGVARCHAR),
            @Result(column = "result", property = "result", jdbcType = JdbcType.LONGVARCHAR)

    })
    List<CmpResult> selectByExample(CmpResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "id, service, container, params, result",
            "from t_cmp_result",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "service", property = "service", jdbcType = JdbcType.VARCHAR),
            @Result(column = "container", property = "container", jdbcType = JdbcType.VARCHAR),
            @Result(column = "params", property = "params", jdbcType = JdbcType.LONGVARCHAR),
            @Result(column = "result", property = "result", jdbcType = JdbcType.LONGVARCHAR)
    })
    CmpResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @UpdateProvider(type = CmpResultSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CmpResult record, @Param("example") CmpResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @UpdateProvider(type = CmpResultSqlProvider.class, method = "updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") CmpResult record, @Param("example") CmpResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @UpdateProvider(type = CmpResultSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") CmpResult record, @Param("example") CmpResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @UpdateProvider(type = CmpResultSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CmpResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @Update({
            "update t_cmp_result",
            "set service = #{service,jdbcType=VARCHAR},",
            "container = #{container,jdbcType=VARCHAR},",
            "params = #{params,jdbcType=LONGVARCHAR},",
            "result = #{result,jdbcType=LONGVARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(CmpResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cmp_result
     *
     * @mbggenerated
     */
    @Update({
            "update t_cmp_result",
            "set service = #{service,jdbcType=VARCHAR},",
            "container = #{container,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CmpResult record);
}